 import "dotlin/dotlin_tools.dt.g.dart" show DotlinTools$Companion;
 import "package:dotlin/src/kotlin/ranges/ranges_ext.dt.g.dart" show IntRangeFactoryExt;
 import "package:dotlin/src/kotlin/library.dt.g.dart" show SafeStringPlus;
 import "dotlin/dotlin_char.dt.g.dart" show DotlinChar;
 import "package:dotlin/src/dotlin/intrinsics/internal.dt.g.dart" show $Return;
 import "dart_format_exception.dt.g.dart" show DartFormatException;
 import "package:dotlin/src/kotlin/ranges/ranges.dt.g.dart" show IntRange;
 import "package:meta/meta.dart" ;
@sealed class Tools{ static const Tools$Companion  $companion = Tools$Companion.$instance; static bool isWhitespace(DotlinChar c)=> Tools$Companion.$instance.$isWhitespace(c); static bool isClosingBracket(DotlinChar c)=> Tools$Companion.$instance.$isClosingBracket(c); static bool isOpeningBracket(DotlinChar c)=> Tools$Companion.$instance.$isOpeningBracket(c); static String _charsToDisplayString1(List<DotlinChar> chars)=> Tools$Companion.$instance._$charsToDisplayString1(chars); static String charsToDisplayString2(List<DotlinChar> chars)=> Tools$Companion.$instance.$charsToDisplayString2(chars); static String _toDisplayString1(String s)=> Tools$Companion.$instance._$toDisplayString1(s); static String toDisplayString2(String s)=> Tools$Companion.$instance.$toDisplayString2(s); static String _toDisplayString1$7cd0f98453dbab0c(DotlinChar c)=> Tools$Companion.$instance._$toDisplayString1$7b03bb44978a4d68(c); static String toDisplayString2$c5d82b9ce5a62f(DotlinChar c)=> Tools$Companion.$instance.$toDisplayString2$m3975160dbe00d095(c); static String _stringsToDisplayString1(List<String> strings)=> Tools$Companion.$instance._$stringsToDisplayString1(strings); static DotlinChar getOpeningBracket(DotlinChar closingBracket)=> Tools$Companion.$instance.$getOpeningBracket(closingBracket);}
@sealed class Tools$Companion{ const  Tools$Companion._() : super();@nonVirtual bool $isWhitespace(DotlinChar c){return DotlinTools$Companion.$instance.$contains("\n\r\t ", c);}@nonVirtual bool $isClosingBracket(DotlinChar c){return DotlinTools$Companion.$instance.$contains("})]", c);}@nonVirtual bool $isOpeningBracket(DotlinChar c){return DotlinTools$Companion.$instance.$contains("{([", c);}@nonVirtual String _$charsToDisplayString1(List<DotlinChar> chars){ String  result = "";for ( int  i = 0; i < chars.length; i += 1) result += this._$toDisplayString1$7b03bb44978a4d68(chars[i]);return result;}@nonVirtual String $charsToDisplayString2(List<DotlinChar> chars){return "[" + this._$charsToDisplayString1(chars) + "]";}@nonVirtual String _$toDisplayString1(String s){return DotlinTools$Companion.$instance.$replace(DotlinTools$Companion.$instance.$replace(s, DotlinChar("\r"), "\\r"), DotlinChar("\n"), "\\n");}@nonVirtual String $toDisplayString2(String s){return "\"" + this._$toDisplayString1(s) + "\"";}@nonVirtual String _$toDisplayString1$7b03bb44978a4d68(DotlinChar c){return this._$toDisplayString1(c.value);}@nonVirtual String $toDisplayString2$m3975160dbe00d095(DotlinChar c){return "'" + this._$toDisplayString1$7b03bb44978a4d68(c) + "'";}@nonVirtual String _$stringsToDisplayString1(List<String> strings){ String  result = "";for ( int  i = 0; i < strings.length; i += 1) result += this._$toDisplayString1(strings[i]);return result;}@nonVirtual DotlinChar $getOpeningBracket(DotlinChar closingBracket){try {final String  tmp0_subject = closingBracket.value;if (tmp0_subject == "}"){throw $Return<DotlinChar>(DotlinChar("{"), -1475888898);}else if (tmp0_subject == ")"){throw $Return<DotlinChar>(DotlinChar("("), -1475888898);}else if (tmp0_subject == "]"){throw $Return<DotlinChar>(DotlinChar("["), -1475888898);}else {throw DartFormatException("Unexpected closing bracket: ${closingBracket}");}}on $Return<DotlinChar> catch (tmp0_return){if (tmp0_return.target == -1475888898){return tmp0_return.value;}else {throw tmp0_return;}} } static const Tools$Companion  $instance = const Tools$Companion._();}